#!/usr/bin/env python3
"""
Aggregate K (lookahead breadth) ablation at N=50.

Usage:
  python scripts/analysis/aggregate_kablation.py
  python scripts/analysis/aggregate_kablation.py --write-tex paper/neurips_ace_2026/figs/tab_kablation.tex
"""
import argparse
import csv
import os
import statistics as st
import sys

sys.path.insert(0, os.path.dirname(__file__))
from scaling_common import K_VALUES, latest_file, metrics_cost, summarize_seed_dir

SEEDS = [42, 123, 456]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default="results/scaling_kablation")
    ap.add_argument("--out", default=None)
    ap.add_argument("--write-tex", default=None)
    args = ap.parse_args()

    root = args.root
    out = args.out or os.path.join(root, "aggregate.csv")
    if not os.path.isdir(root):
        print(f"ERROR: root not found: {root}", file=sys.stderr)
        sys.exit(1)

    rows = []
    for k in K_VALUES:
        kroot = os.path.join(root, f"K{k}")
        for seed in SEEDS:
            seed_dir = os.path.join(kroot, "nodes50", "ace", f"seed_{seed}")
            status = "missing"
            summ = None
            src = ""
            cost = {}
            if os.path.isdir(seed_dir):
                summ = summarize_seed_dir(seed_dir)
                src = latest_file(seed_dir, "node_losses.csv") or ""
                cost = metrics_cost(seed_dir)
                if summ:
                    status = "ok"
            row = {"K": k, "seed": seed, "status": status, "source_csv": src}
            if summ:
                row.update({
                    "n_episodes": summ["n_ep"],
                    "n_nodes": summ["n_nodes"],
                    "best_episode": summ["best_episode"],
                    "best_mse": f"{summ['best']:.6f}",
                    "best_mse_per_node": f"{summ['per_node_best']:.6f}",
                    **{key: (f"{v:.2f}" if v == v else "")
                       for key, v in cost.items()},
                })
            else:
                row.update({
                    "n_episodes": 0, "n_nodes": 0, "best_episode": "",
                    "best_mse": "", "best_mse_per_node": "",
                    "prompt_tokens_mean": "", "peak_vram_gb": "",
                })
            rows.append(row)

    fieldnames = [
        "K", "seed", "n_episodes", "n_nodes", "best_episode",
        "best_mse", "best_mse_per_node",
        "prompt_tokens_mean", "peak_vram_gb", "status", "source_csv",
    ]
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        for row in rows:
            w.writerow({key: row.get(key, "") for key in fieldnames})

    print(f"Wrote {out} ({len(rows)} rows)\n")
    cell_stats = []
    print(f"{'K':>3} {'seed':>5} {'n_ep':>5} {'bestEp':>6} {'best/node':>10}  status")
    print("-" * 45)
    for row in rows:
        print(f"{row['K']:>3} {row['seed']:>5} {row.get('n_episodes', 0):>5} "
              f"{str(row.get('best_episode', '')):>6} "
              f"{row.get('best_mse_per_node', ''):>10}  {row['status']}")

    print("\nPer-K aggregate:")
    for k in K_VALUES:
        cell = [r for r in rows if r["K"] == k and r["status"] == "ok"]
        n = len(cell)
        if n == 0:
            continue
        per_nodes = [float(r["best_mse_per_node"]) for r in cell]
        n_eps = [int(r["n_episodes"]) for r in cell]
        toks = [float(r["prompt_tokens_mean"]) for r in cell
                if r.get("prompt_tokens_mean")]
        vrams = [float(r["peak_vram_gb"]) for r in cell if r.get("peak_vram_gb")]
        cell_stats.append({
            "K": k, "n": n,
            "pm": st.mean(per_nodes),
            "ps": st.stdev(per_nodes) if n > 1 else 0.0,
            "em": st.mean(n_eps),
            "tm": st.mean(toks) if toks else float("nan"),
            "vm": st.mean(vrams) if vrams else float("nan"),
        })
        print(f"  K={k}  n={n}  per-node={st.mean(per_nodes):.4f}  ep={st.mean(n_eps):.0f}")

    if args.write_tex and cell_stats:
        tex_path = args.write_tex
        os.makedirs(os.path.dirname(tex_path) or ".", exist_ok=True)
        lines = [
            "% Auto-generated by scripts/analysis/aggregate_kablation.py",
            "\\begin{table}[h]",
            "\\centering",
            "\\caption{Lookahead breadth $K$ ablation at $N{=}50$ (compact prompt, "
            "$m{=}8$ salient nodes). Per-node best MSE and mean prompt tokens "
            "(cost proxy) vs.\\ $K$.}",
            "\\label{tab:k-ablation}",
            "\\small",
            "\\begin{tabular}{@{}rccccc@{}}",
            "\\toprule",
            "$K$ & Seeds & Best per-node MSE & Episodes (mean) & "
            "Prompt tokens & Peak VRAM (GB) \\\\",
            "\\midrule",
        ]
        for s in cell_stats:
            pm_str = f"${s['pm']:.3f}" + (f"$\\pm${s['ps']:.3f}" if s["n"] > 1 else "")
            tm_str = f"{s['tm']:.0f}" if s["tm"] == s["tm"] else "---"
            vm_str = f"{s['vm']:.1f}" if s["vm"] == s["vm"] else "---"
            lines.append(
                f"{s['K']} & {s['n']} & {pm_str} & {s['em']:.0f} & "
                f"{tm_str} & {vm_str} \\\\"
            )
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"\nWrote LaTeX table: {tex_path}")


if __name__ == "__main__":
    main()
