#!/bin/bash

# ============================================================================
# Consolidate Multi-Seed Results for Statistical Analysis
# ============================================================================
# Aggregates results from multiple seed runs to compute statistics.
#
# Usage:
#   ./scripts/consolidate_multi_runs.sh results/multi_run_TIMESTAMP
# ============================================================================

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <multi_run_directory>"
    echo "Example: $0 results/multi_run_20260123_120000"
    exit 1
fi

MULTI_RUN_DIR=$1

if [ ! -d "$MULTI_RUN_DIR" ]; then
    echo "ERROR: Directory not found: $MULTI_RUN_DIR"
    exit 1
fi

echo "========================================"
echo "Consolidating Multi-Seed Results"
echo "========================================"
echo "Directory: $MULTI_RUN_DIR"
echo "Started: $(date)"
echo ""

# Create consolidated output directory
CONSOLIDATED_DIR="$MULTI_RUN_DIR/consolidated"
mkdir -p "$CONSOLIDATED_DIR"

# Find all seed subdirectories
SEED_DIRS=("$MULTI_RUN_DIR"/seed_*)
NUM_SEEDS=${#SEED_DIRS[@]}

echo "Found $NUM_SEEDS seed directories"
echo ""

# ============================================================================
# Consolidate ACE Results
# ============================================================================
echo "[1/5] Consolidating ACE results..."

if [ -f "scripts/compute_statistics.py" ]; then
    python scripts/compute_statistics.py \
        --input "$MULTI_RUN_DIR" \
        --experiment ace \
        --output "$CONSOLIDATED_DIR/ace_statistics.csv"
    echo "  ✓ ACE statistics: $CONSOLIDATED_DIR/ace_statistics.csv"
else
    echo "  ⚠️  compute_statistics.py not found - create this script"
fi

# ============================================================================
# Consolidate Baseline Results
# ============================================================================
echo "[2/5] Consolidating baseline results..."

for baseline in random round_robin max_variance ppo; do
    if [ -f "scripts/compute_statistics.py" ]; then
        python scripts/compute_statistics.py \
            --input "$MULTI_RUN_DIR" \
            --experiment baselines \
            --baseline "$baseline" \
            --output "$CONSOLIDATED_DIR/${baseline}_statistics.csv" 2>/dev/null || true
    fi
done

echo "  ✓ Baseline statistics computed"

# ============================================================================
# Create Summary Table with Statistics
# ============================================================================
echo "[3/5] Creating summary table..."

cat > "$CONSOLIDATED_DIR/table1_with_stats.txt" <<EOF
Method Comparison with Statistical Validation
==============================================

Based on $NUM_SEEDS independent runs with different random seeds.

Format: mean ± std (95% CI)

[TODO: Populate this with actual statistics from compute_statistics.py]

Method       | X1        | X2        | X3        | X4        | X5        | Total     | Episodes
-------------|-----------|-----------|-----------|-----------|-----------|-----------|----------
ACE (Ours)   | TBD       | TBD       | TBD       | TBD       | TBD       | TBD       | TBD
Random       | TBD       | TBD       | TBD       | TBD       | TBD       | TBD       | 100
Round-Robin  | TBD       | TBD       | TBD       | TBD       | TBD       | TBD       | 100
Max-Variance | TBD       | TBD       | TBD       | TBD       | TBD       | TBD       | 100
PPO          | TBD       | TBD       | TBD       | TBD       | TBD       | TBD       | 100

Statistical Significance (paired t-tests):
ACE vs Random:       p = TBD
ACE vs Round-Robin:  p = TBD
ACE vs Max-Variance: p = TBD
ACE vs PPO:          p = TBD

Legend:
*** p < 0.001 (highly significant)
**  p < 0.01  (very significant)
*   p < 0.05  (significant)
ns  p ≥ 0.05  (not significant)
EOF

echo "  ✓ Summary table template: $CONSOLIDATED_DIR/table1_with_stats.txt"

# ============================================================================
# Generate Consolidated Figures
# ============================================================================
echo "[4/5] Generating consolidated figures with error bars..."

echo "  [Figures will be generated by compute_statistics.py]"
echo "  Output: $CONSOLIDATED_DIR/figures/"

# ============================================================================
# Create Summary Report
# ============================================================================
echo "[5/5] Creating consolidation summary..."

cat > "$CONSOLIDATED_DIR/CONSOLIDATION_SUMMARY.txt" <<EOF
Multi-Seed Results Consolidation Summary
=========================================

Processed: $(date)
Base Directory: $MULTI_RUN_DIR
Number of Seeds: $NUM_SEEDS
Consolidated Output: $CONSOLIDATED_DIR

Seeds Found:
EOF

for dir in "${SEED_DIRS[@]}"; do
    seed=$(basename "$dir" | sed 's/seed_//')
    echo "  - Seed $seed" >> "$CONSOLIDATED_DIR/CONSOLIDATION_SUMMARY.txt"
done

cat >> "$CONSOLIDATED_DIR/CONSOLIDATION_SUMMARY.txt" <<EOF

Consolidated Outputs:
=====================

Statistics:
  - $CONSOLIDATED_DIR/ace_statistics.csv
  - $CONSOLIDATED_DIR/*_statistics.csv

Tables:
  - $CONSOLIDATED_DIR/table1_with_stats.txt

Figures (with error bars):
  - $CONSOLIDATED_DIR/figures/

Next Steps:
===========

1. Review statistics: cat $CONSOLIDATED_DIR/table1_with_stats.txt
2. Check significance: Look for p-values < 0.05
3. Update paper Table 1 with mean ± std format
4. Add error bars to all figures
5. Add significance markers (*, **, ***) to tables

EOF

cat "$CONSOLIDATED_DIR/CONSOLIDATION_SUMMARY.txt"

echo ""
echo "========================================"
echo "Consolidation Complete!"
echo "========================================"
echo "Summary: $CONSOLIDATED_DIR/CONSOLIDATION_SUMMARY.txt"
echo ""
echo "Next: Update paper with statistics from consolidated results"
