"""Generate retained empirical LaTeX claims from the validated sealed receipt."""
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
folder=ROOT/'results/delivery_final_history_20261006'
raw=(folder/'scores.json').read_bytes();stats=json.loads((folder/'independent_statistics.json').read_text())
assert hashlib.sha256(raw).hexdigest()==stats['score_sha256'] and stats['matches_receipt']
pairs=json.loads(raw)['pairs'];assert len(pairs)==stats['n']==12
w=stats['worsening_histories'];assert len(w)==1 and w[0]['seed']==124753321
macros={'DeliveryN':str(stats['n']),'DeliveryRatio':f"{stats['ratio']:.3f}",
        'DeliveryCILow':f"{stats['ci_lo']:.3f}",'DeliveryCIHigh':f"{stats['ci_hi']:.3f}",
        'DeliveryP':f"{stats['exact_sign_flip_p']:.8f}",'DeliveryWins':str(len(pairs)-len(w)),
        'WorseSeed':str(w[0]['seed']),'WorseOnline':f"{w[0]['online_error']:.6f}",
        'WorseDelivery':f"{w[0]['delivery_median_error']:.6f}",'WorseRatio':f"{w[0]['ratio']:.6f}"}
tex='% Generated by scripts/research/generate_delivery_claims.py; do not hand edit.\n'
tex+='\n'.join('\\newcommand{\\'+name+'}{'+value+'}' for name,value in macros.items())+'\n'
(ROOT/'paper/aistats_ace_2027/delivery_claims.tex').write_text(tex)
index={'scores_sha256':hashlib.sha256(raw).hexdigest(),
       'statistics_sha256':hashlib.sha256((folder/'independent_statistics.json').read_bytes()).hexdigest(),
       'generator_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
       'macros':macros,'scope':'12 histories of one emulator, median scored optimization performance, full exposed grid',
       'pending_claims':['causal architecture attribution','equal-compute advantage','prospective generalization','external physical superiority'],
       'removed_claims':['acquisition superiority','foundation-model benefit','DPO optimality','unrestricted causal identification','generic MSE gain equals mutual information']}
(ROOT/'paper/aistats_ace_2027/claim_index.json').write_text(json.dumps(index,indent=2)+'\n')
